#!/data/data/com.termux/files/usr/bin/bash

# Doc Generator Skill - Main Script
# Usage: ./doc-gen.sh [api|functions|readme|architecture]

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
OUTPUT_DIR="./docs"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

MODE="${1:-full}"

echo -e "\n${CYAN}╔════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║        📝 DOCUMENTATION GENERATOR      ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════╝${NC}"
echo -e "Mode: ${YELLOW}${MODE}${NC}\n"

# Create docs directory
mkdir -p "$OUTPUT_DIR"

# Generate README
generate_readme() {
    echo -e "${BLUE}📄 Generating README.md...${NC}"
    
    README_FILE="./README.md"
    
    # Check if README exists
    if [ -f "$README_FILE" ]; then
        echo -e "  ${YELLOW}README.md exists - creating backup${NC}"
        cp "$README_FILE" "${README_FILE}.${TIMESTAMP}.bak"
    fi
    
    # Get project name
    PROJECT_NAME=$(basename "$(pwd)")
    
    # Check for package.json
    HAS_PACKAGE=false
    if [ -f "package.json" ]; then
        HAS_PACKAGE=true
        DESCRIPTION=$(grep -o '"description": *"[^"]*"' package.json | cut -d'"' -f4 || echo "")
        VERSION=$(grep -o '"version": *"[^"]*"' package.json | cut -d'"' -f4 || echo "1.0.0")
    fi
    
    cat > "$README_FILE" << 'HEADER'
HEADER
    
    cat > "$README_FILE" << EOF
# ${PROJECT_NAME}

${DESCRIPTION:-A project under development}

**Version:** ${VERSION:-1.0.0}  
**Generated:** ${TIMESTAMP}

## 📋 Overview

<!-- Add project description -->

## 🚀 Getting Started

\`\`\`bash
# Install dependencies
npm install

# Start the application
npm start

# Run tests
npm test
\`\`\`

## 📁 Project Structure

\`\`\`
$(find . -maxdepth 2 -not -path '*/node_modules/*' -not -path '*/.git/*' -not -path '*/.cache/*' | head -30 | sed 's|^\./||')
\`\`\`

## 🛠️ Technologies

<!-- Add your tech stack -->

## 📖 API Documentation

See [docs/api.md](docs/api.md) for API details.

## 🧪 Testing

\`\`\`bash
npm test
\`\`\`

## 📝 License

<!-- Add license info -->

---
*Generated by doc-gen skill*
EOF
    
    echo -e "  ${GREEN}✅ README.md generated${NC}"
}

# Document functions
generate_function_docs() {
    echo -e "${BLUE}📋 Scanning functions...${NC}"
    
    OUTPUT_FILE="$OUTPUT_DIR/functions.md"
    
    cat > "$OUTPUT_FILE" << EOF
# Function Documentation
**Generated:** ${TIMESTAMP}

EOF
    
    # Scan JavaScript/TypeScript files
    if ls src/**/*.js src/**/*.ts 2>/dev/null | head -1 &>/dev/null || ls *.js *.ts 2>/dev/null | head -1 &>/dev/null; then
        echo "## JavaScript/TypeScript Functions" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        
        find . -name "*.js" -o -name "*.ts" 2>/dev/null | grep -v node_modules | grep -v .cache | while read -r file; do
            # Extract function names
            FUNCTIONS=$(grep -E "(function\s|const\s+\w+\s*=\s*(async\s+)?\(|=>\s*\{)" "$file" 2>/dev/null | head -10 || true)
            if [ -n "$FUNCTIONS" ]; then
                echo "### $file" >> "$OUTPUT_FILE"
                echo "\`\`\`" >> "$OUTPUT_FILE"
                echo "$FUNCTIONS" >> "$OUTPUT_FILE"
                echo "\`\`\`" >> "$OUTPUT_FILE"
                echo "" >> "$OUTPUT_FILE"
            fi
        done
    fi
    
    # Scan Python files
    if ls **/*.py 2>/dev/null | head -1 &>/dev/null; then
        echo "## Python Functions" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        
        find . -name "*.py" 2>/dev/null | grep -v __pycache__ | while read -r file; do
            FUNCTIONS=$(grep -E "(def\s+\w+)" "$file" 2>/dev/null | head -10 || true)
            if [ -n "$FUNCTIONS" ]; then
                echo "### $file" >> "$OUTPUT_FILE"
                echo "\`\`\`" >> "$OUTPUT_FILE"
                echo "$FUNCTIONS" >> "$OUTPUT_FILE"
                echo "\`\`\`" >> "$OUTPUT_FILE"
                echo "" >> "$OUTPUT_FILE"
            fi
        done
    fi
    
    echo -e "  ${GREEN}✅ Function documentation generated${NC}"
}

# Generate architecture docs
generate_architecture() {
    echo -e "${BLUE}🏗️ Generating architecture docs...${NC}"
    
    ARCH_FILE="$OUTPUT_DIR/architecture.md"
    
    cat > "$ARCH_FILE" << EOF
# Architecture Documentation
**Generated:** ${TIMESTAMP}

## System Overview

<!-- Add system architecture description -->

## Directory Structure

\`\`\`
$(tree -L 3 -I 'node_modules|.git|.cache' . 2>/dev/null || find . -maxdepth 3 -not -path '*/node_modules/*' -not -path '*/.git/*' -not -path '*/.cache/*' | head -50)
\`\`\`

## Dependencies

EOF
    
    # List dependencies
    if [ -f "package.json" ]; then
        echo "### Node.js Dependencies" >> "$ARCH_FILE"
        echo "" >> "$ARCH_FILE"
        echo "\`\`\`json" >> "$ARCH_FILE"
        grep -A 100 '"dependencies"' package.json | grep -B 100 '}' | head -20 >> "$ARCH_FILE" 2>/dev/null || echo "{}" >> "$ARCH_FILE"
        echo "\`\`\`" >> "$ARCH_FILE"
        echo "" >> "$ARCH_FILE"
    fi
    
    if [ -f "requirements.txt" ]; then
        echo "### Python Dependencies" >> "$ARCH_FILE"
        echo "" >> "$ARCH_FILE"
        echo "\`\`\`" >> "$ARCH_FILE"
        cat requirements.txt >> "$ARCH_FILE" 2>/dev/null
        echo "\`\`\`" >> "$ARCH_FILE"
    fi
    
    echo -e "  ${GREEN}✅ Architecture documentation generated${NC}"
}

# Generate API docs
generate_api_docs() {
    echo -e "${BLUE}🔌 Generating API documentation...${NC}"
    
    API_FILE="$OUTPUT_DIR/api.md"
    
    cat > "$API_FILE" << EOF
# API Documentation
**Generated:** ${TIMESTAMP}

## Endpoints

<!-- Document your API endpoints -->

| Method | Endpoint | Description |
|--------|----------|-------------|
| GET | /health | Health check |
| GET | /api/v1/* | API routes |

## Authentication

<!-- Add auth details -->

## Error Codes

| Code | Description |
|------|-------------|
| 400 | Bad Request |
| 401 | Unauthorized |
| 404 | Not Found |
| 500 | Internal Server Error |

EOF
    
    # Scan for route definitions
    if ls src/**/*.js src/**/*.ts routes/**/*.js 2>/dev/null | head -1 &>/dev/null; then
        echo "## Detected Routes" >> "$API_FILE"
        echo "" >> "$API_FILE"
        
        find . -type f \( -name "*.js" -o -name "*.ts" \) 2>/dev/null | grep -v node_modules | grep -v .cache | while read -r file; do
            ROUTES=$(grep -E "(app\.(get|post|put|delete|patch)|router\.(get|post|put|delete|patch)|@app\.route|@router\.route)" "$file" 2>/dev/null || true)
            if [ -n "$ROUTES" ]; then
                echo "### $file" >> "$API_FILE"
                echo "\`\`\`" >> "$API_FILE"
                echo "$ROUTES" >> "$API_FILE"
                echo "\`\`\`" >> "$API_FILE"
                echo "" >> "$API_FILE"
            fi
        done
    fi
    
    echo -e "  ${GREEN}✅ API documentation generated${NC}"
}

# Execute based on mode
case "$MODE" in
    readme)
        generate_readme
        ;;
    functions)
        generate_function_docs
        ;;
    architecture)
        generate_architecture
        ;;
    api)
        generate_api_docs
        ;;
    full)
        generate_readme
        generate_function_docs
        generate_architecture
        generate_api_docs
        ;;
    *)
        echo -e "${YELLOW}Usage: $0 [readme|functions|architecture|api|full]${NC}"
        exit 1
        ;;
esac

echo -e "\n${GREEN}╔════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║        ✅ DOCS GENERATED SUCCESSFULLY   ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════╝${NC}"
echo -e "Output: ${CYAN}${OUTPUT_DIR}/${NC}\n"
